# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7168eb6cbb4245dbfbf1f5609a70f2f4fcc3b76066785572d7a5f5f82c5f7cf79863dd133b43913b2ff470b54d589e9f91f306ea6c95571e7ac3d78d6c8782d6

test:
  secret_key_base: f98b8dbaa5ddbfca2f2ba05225c3e79858541cff7974905b45743a0a0d5e56ca622f0f64c69f46d1e97c76629b946d1aff62985e96235a0b98e3e7728d24edff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
